[package]
name = "Tompilery"
version = "0.1.0"
authors = ["ZhengHaoWen <705680835@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spectral = "0.6.0"
[dev-dependencies]